name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Increment versionCode and set versionName in libs.versions.toml
        run: |
          chmod +x ./update_version.sh
          sh ./update_version.sh ${{ github.ref_name }}

      - name: Stage version file changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          branch: main
          commit_message: 🎊🎉 Release version ${{ github.ref_name }} 🎉🎊

      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug

      - name: List APK output
        run: ls -al ./app/build/outputs/apk/debug/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shelfdroid-${{ github.ref_name }}.apk
          path: |
            ./app/build/outputs/apk/debug/
            
      - name: Rename APK with tag name
        run: |
          mv ./app/build/outputs/apk/debug/app-debug.apk ./app/build/outputs/apk/debug/shelfdroid-${{ github.ref_name }}.apk

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./app/build/outputs/apk/debug/shelfdroid-${{ github.ref_name }}.apk